model_type: ecd
split:
    type: hash
    column: Store_id
    probabilities:
    - 0.7
    - 0.15
    - 0.15
input_features:
  - name: Sales
    type: sequence
    encoder: parallel_cnn
    reduce_output: null
  - name: Order
    type: sequence
    encoder: parallel_cnn
    reduce_output: null
  - name: Discount
    type: sequence
    encoder: parallel_cnn
    reduce_output: null
  - name: DayofWeek
    type: sequence
    encoder: parallel_cnn
    reduce_output: null
  - name: MonthOfYear
    type: sequence
    encoder: parallel_cnn
    reduce_output: null
  - name: Holiday
    type: sequence
    encoder: parallel_cnn
    reduce_output: null
combiner:
    type: concat
output_features:
  - name: Sales_sequence_label
    type: sequence
    decoder: tagger
    reduce_input: null
    loss:
         type: sequence_softmax_cross_entropy
trainer:
    epochs: 300
    learning_rate: 0.001
    early_stop: 15
    evaluate_training_set: true
    validation_field: Sales_sequence_label
    validation_metric: sequence_softmax_cross_entropy
