model_type: ecd
split:
    type: hash
    column: Store_id
    probabilities:
    - 0.8
    - 0.1
    - 0.1
input_features:
  - name: Sales
    type: sequence
    encoder: transformer
    reduce_output: null
  - name: Order
    type: sequence
    encoder: transformer
    reduce_output: null
  - name: Discount
    type: sequence
    encoder: transformer
    reduce_output: null
  - name: DayOfWeek
    type: sequence
    encoder: transformer
    reduce_output: null
  - name: MonthOfYear
    type: sequence
    encoder: transformer
    reduce_output: null
  - name: Holiday
    type: sequence
    encoder: transformer
    reduce_output: null
  - name: Store_Type
    type: sequence
    encoder: transformer
    reduce_output: null
  - name: Location_Type
    type: sequence
    encoder: transformer
    reduce_output: null
  - name: Region_Code
    type: sequence
    encoder: transformer
    reduce_output: null
combiner:
    type: transformer
output_features:
  - name: Sales_sequence_label_2019-05-02
    type: number
    loss:
      type: mean_squared_error
  - name: Sales_sequence_label_2019-05-03
    type: number
    loss:
      type: mean_squared_error
  - name: Sales_sequence_label_2019-05-04
    type: number
    loss:
      type: mean_squared_error
  - name: Sales_sequence_label_2019-05-05
    type: number
    loss:
      type: mean_squared_error
  - name: Sales_sequence_label_2019-05-06
    type: number
    loss:
      type: mean_squared_error
  - name: Sales_sequence_label_2019-05-07
    type: number
    loss:
      type: mean_squared_error
  - name: Sales_sequence_label_2019-05-08
    type: number
    loss:
      type: mean_squared_error
  - name: Sales_sequence_label_2019-05-09
    type: number
  - name: Sales_sequence_label_2019-05-10
    type: number
    loss:
      type: mean_squared_error
  - name: Sales_sequence_label_2019-05-11
    type: number
    loss:
      type: mean_squared_error
  - name: Sales_sequence_label_2019-05-12
    type: number
    loss:
      type: mean_squared_error
  - name: Sales_sequence_label_2019-05-13
    type: number
    loss:
      type: mean_squared_error
  - name: Sales_sequence_label_2019-05-14
    type: number
  - name: Sales_sequence_label_2019-05-15
    type: number
    loss:
      type: mean_squared_error
  - name: Sales_sequence_label_2019-05-16
    type: number
    loss:
      type: mean_squared_error
  - name: Sales_sequence_label_2019-05-17
    type: number
    loss:
      type: mean_squared_error
  - name: Sales_sequence_label_2019-05-18
    type: number
    loss:
      type: mean_squared_error
  - name: Sales_sequence_label_2019-05-19
    type: number
    loss:
      type: mean_squared_error
  - name: Sales_sequence_label_2019-05-20
    type: number
    loss:
      type: mean_squared_error
  - name: Sales_sequence_label_2019-05-21
    type: number
    loss:
      type: mean_squared_error
  - name: Sales_sequence_label_2019-05-22
    type: number
  - name: Sales_sequence_label_2019-05-23
    type: number
    loss:
      type: mean_squared_error
  - name: Sales_sequence_label_2019-05-24
    type: number
  - name: Sales_sequence_label_2019-05-25
    type: number
    loss:
      type: mean_squared_error
  - name: Sales_sequence_label_2019-05-26
    type: number
    loss:
      type: mean_squared_error
  - name: Sales_sequence_label_2019-05-27
    type: number
    loss:
      type: mean_squared_error
  - name: Sales_sequence_label_2019-05-28
    type: number
    loss:
      type: mean_squared_error
  - name: Sales_sequence_label_2019-05-29
    type: number
    loss:
      type: mean_squared_error
  - name: Sales_sequence_label_2019-05-30
    type: number
    loss:
      type: mean_squared_error
  - name: Sales_sequence_label_2019-05-31
    type: number
    loss:
      type: mean_squared_error
trainer:
    epochs: 300
    learning_rate: 0.001
    early_stop: 15
    evaluate_training_set: true
