model_type: ecd
split:
    type: hash
    column: Store_id
    probabilities:
    - 0.7
    - 0.15
    - 0.15
input_features:
    - name: Store_Type
      type: category
    - name: Location_Type
      type: category
    - name: Region_Code
      type: category
    - name: DayOfWeek
      type: category
    - name: Holiday
      type: binary
    - name: Discount
      type: category
    - name: MonthOfYear
      type: category
    - name: Sales_previous
      type: timeseries
      tied: null
      encoder: 
          type: parallel_cnn
combiner:
    type: concat
output_features:
    - name: Sales
      type: number
      loss:
          type: mean_squared_error
trainer:
    epochs: 300
    learning_rate: 0.001
    early_stop: 15
    evaluate_training_set: true
    validation_field: Sales
    validation_metric: root_mean_squared_error
