model_type: ecd
split:
    type: hash
    column: Store_id
    probabilities:
    - 0.7
    - 0.15
    - 0.15
input_features:
    - name: Sales
      type: sequence
      tied: null
      encoder: 
          type: parallel_cnn
          embedding_size: 256
      decoder:
          type: tagger
          fc_output_size: 256
    - name: #Order
      type: sequence
      tied: null
      encoder:
          type: parallel_cnn
          embedding_size: 256
      decoder:
          type: tagger
          fc_output_size: 256
    - name: Discount
      type: sequence
      tied: null
      encoder:
          type: parallel_cnn
          embedding_size: 256
      decoder:
          type: tagger
          fc_output_size: 256
    - name: DayofWeek
      type: sequence
      tied: null
      encoder:
          type: parallel_cnn
          embedding_size: 256
      decoder:
          type: tagger
          fc_output_size: 256
    - name: MonthOfYear
      type: sequence
      tied: null
      encoder:
          type: parallel_cnn
          embedding_size: 256
      decoder:
          type: tagger
          fc_output_size: 256
    - name: Holiday
      type: sequence
      tied: null
      encoder:
          type: parallel_cnn
          embedding_size: 256
      decoder:
          type: tagger
          fc_output_size: 256
    - name: Holiday
      type: sequence
      tied: null
      encoder:
          type: parallel_cnn
          embedding_size: 256
      decoder:
          type: tagger
          fc_output_size: 256 
combiner:
    type: concat
output_features:
    - name: Sales_sequence_label
      type: sequence
      tied: null
      encoder:
          type: parallel_cnn
          embedding_size: 256
      decoder:
          type: tagger
          fc_output_size: 60
      loss:
          type: mean_squared_error
trainer:
    epochs: 300
    learning_rate: 0.001
    early_stop: 15
    evaluate_training_set: true
    validation_field: Sales
    validation_metric: mean_squared_error
